
Create table tranFRMLOCATION(
[Location ID] nvarchar(63) not null primary key,
[1 mile pop] nvarchar(255),
[3 mile pop] nvarchar(255),
[5 mile pop] nvarchar(255),
[AverageTerm] nvarchar(255),
[Avg  monthly gross personal training revenue] nvarchar(255),
[Gross Rent] nvarchar(255),
[Hours of Operation] nvarchar(255), 
[Median income > $50000] nvarchar(255),
[Members  Dues and PIF] nvarchar(255),
[Monthly Fee Amt] nvarchar(255),
[Multi-Purpose Sq Ft] nvarchar(255),
[Number of Rooms] nvarchar(255),
[Payroll] nvarchar(255),
[Percent Owner 1] nvarchar(255),
[Percent Owner 2] nvarchar(255),
[Percent Owner 3] nvarchar(255),
[Percent Owner 4] nvarchar(255),
[Percent Owner 5] nvarchar(255),
[Percent Owner 6] nvarchar(255),
[Person  Training Revenue] nvarchar(255),
[Personal Training Revenue] nvarchar(255),
[Problem %] nvarchar(255),
[Profit Loss] nvarchar(255),
[Remit Amount Last Quarter] nvarchar(255),
[Remit Amount Quarter Change] nvarchar(255),
[Territory] nvarchar(255),
[Total Contracts] nvarchar(255),
[Transfer Fee] nvarchar(15),
[Utilities] nvarchar(255),
[Average Contract Value] nvarchar(255),
[Average Member Value] nvarchar(255),
[BOE] nvarchar(255),
[Draft %] nvarchar(255),
[Dues] nvarchar(255),
[Exited Agreements] nvarchar(255),
[Monthly Attrition] nvarchar(255),
[NEW Agreements] nvarchar(255),
[PIF %] nvarchar(255),
[Remit Amount] nvarchar(255),
[Renewal Fee] nvarchar(255),
[Rolling 12 Month Attrition] nvarchar(255),
[Sq Ft] nvarchar(15),
[Total Rent] nvarchar(255)
)