CREATE TABLE [dbo].[TaLocation] (
    [Location_ID]                                 NVARCHAR (63)   NOT NULL,
    [TLD_Location_ID]                             NVARCHAR (63)   NOT NULL,
    [TLI_Location_ID]                             NVARCHAR (63)   NOT NULL,
    [TLPI_Location_ID]                            NVARCHAR (63)   NOT NULL,
    [mile_pop_1]                                  BIGINT          NULL,
    [mile_pop_3]                                  BIGINT          NULL,
    [mile_pop_5]                                  BIGINT          NULL,
    [AverageTerm]                                 NUMERIC (18, 6) NULL,
    [Avg_monthly_gross_personal_training_revenue] NVARCHAR (127)  NULL,
    [Gross_Rent]                                  NUMERIC (18, 6) NULL,
    [Hours_of_Operation]                          BIGINT          NULL,
    [Median_income_50000]                         BIGINT          NULL,
    [Members_Dues_and_PIF]                        BIGINT          NULL,
    [Monthly_Fee_Amt]                             NUMERIC (18, 6) NULL,
    [MultiPurpose_Sq_Ft]                          BIGINT          NULL,
    [Number_of_Rooms]                             BIGINT          NULL,
    [Payroll]                                     NUMERIC (18, 6) NULL,
    [Percent_Owner_1]                             NUMERIC (18, 6) NULL,
    [Percent_Owner_2]                             NUMERIC (18, 6) NULL,
    [Percent_Owner_3]                             NUMERIC (18, 6) NULL,
    [Percent_Owner_4]                             NUMERIC (18, 6) NULL,
    [Percent_Owner_5]                             NUMERIC (18, 6) NULL,
    [Percent_Owner_6]                             BIGINT          NULL,
    [Person_Training_Revenue]                     NVARCHAR (127)  NULL,
    [Personal_Training_Revenue]                   NUMERIC (18, 6) NULL,
    [Problem_]                                    NUMERIC (18, 6) NULL,
    [Profit_Loss]                                 NUMERIC (18, 6) NULL,
    [Remit_Amount_Last_Quarter]                   NUMERIC (18, 6) NULL,
    [Remit_Amount_Quarter_Change]                 NUMERIC (18, 6) NULL,
    [Total_Contracts]                             BIGINT          NULL,
    [Transfer_Fee]                                NVARCHAR (15)   NULL,
    [Utilities]                                   NUMERIC (18, 6) NULL,
    [Average_Contract_Value]                      NUMERIC (18, 6) NULL,
    [Average_Member_Value]                        NUMERIC (18, 6) NULL,
    [BOE]                                         NUMERIC (18, 6) NULL,
    [Draft_]                                      NUMERIC (18, 6) NULL,
    [Dues]                                        NUMERIC (18, 6) NULL,
    [Exited_Agreements]                           BIGINT          NULL,
    [Monthly_Attrition]                           NUMERIC (18, 6) NULL,
    [NEW_Agreements]                              BIGINT          NULL,
    [PIF_]                                        NUMERIC (18, 6) NULL,
    [Remit_Amount]                                NUMERIC (18, 6) NULL,
    [Renewal_Fee]                                 BIGINT          NULL,
    [Rolling_12_Month_Attrition]                  NUMERIC (18, 6) NULL,
    [Sq_Ft]                                       NVARCHAR (15)   NULL,
    [Total_Rent]                                  NUMERIC (18, 6) NULL,
    CONSTRAINT [FK_TaLocationDate] FOREIGN KEY ([TLD_Location_ID]) REFERENCES [dbo].[TaLocationDate] ([TLD_Location_ID]),
    CONSTRAINT [FK_TaLocationInformation] FOREIGN KEY ([TLI_Location_ID]) REFERENCES [dbo].[TaLocationInformation] ([TLI_Location_ID]),
    CONSTRAINT [FK_TaLocationPersonalInformation] FOREIGN KEY ([TLPI_Location_ID]) REFERENCES [dbo].[TaLocationPersonalInformation] ([TLPI_Location_ID])
);

