-- =============================================        
-- Description: <Description,,>        
-- exec [usp_DataAnalysis] @TABLE_NAME='TaLocation'      
-- =============================================      
CREATE PROCEDURE [usp_LocationRawtoTables]
AS      
BEGIN      
SET NOCOUNT ON
BEGIN TRANSACTION
BEGIN TRY
INSERT INTO [TaLocationDate]
(
[TLD_Location_ID]
,[Actual_Opening]
,[BOE_Verified]
,[Close_Date]
,[Opened_On]
,[Original_Franchisee_Open_Date]
,[Sale_Date]
,[Agreement_Renewal_Date]
,[Agreement_Signed]
,[Created_On]
,[Modified_On]
)
SELECT [Location_ID]
,CONVERT(DATE,[Actual_Opening],105) AS [Actual_Opening]
,CONVERT(DATE,[BOE_Verified],105) AS [BOE_Verified]
,CONVERT(DATE,[Close_Date],105) AS [Close_Date]
,CONVERT(DATE,[Opened_On],105) AS [Opened_On]
,CONVERT(DATE,[Original_Franchisee_Open_Date],105) AS [Original_Franchisee_Open_Date]
,CONVERT(DATE,[Sale_Date],105) AS [Sale_Date]
,CONVERT(DATE,[Agreement_Renewal_Date],105) AS [Agreement_Renewal_Date]
,CONVERT(DATE,[Agreement_Signed],105) AS [Agreement_Signed]
,CONVERT(DATE,[Created_On],105) AS [Created_On]
,CONVERT(DATE,[Modified_On],105) AS [Modified_On]
FROM [dbo].[TaLocationRaw]
WHERE [Location_ID] NOT IN (
SELECT
[TLD_Location_ID]
FROM [TaLocationDate]
)

INSERT INTO [TaLocationInformation]
(
[TLI_Location_ID]
,[Location_Type]
,[Territory]
,[City]
,[Country]
,[Latitude]
,[Location]
,[Location_]
,[Longitude]
,[State]
,[Time_Zone]
,[ZIP_Postal_Code]
,[Differentiator]
)
SELECT [Location_ID]
,[Location_Type]
,[Territory]
,[City]
,[Country]
,[Latitude]
,[Location]
,[Location_]
,[Longitude]
,[State]
,[Time_Zone]
,[ZIP_Postal_Code]
,[Differentiator]
FROM [dbo].[TaLocationRaw]
WHERE [Location_ID] NOT IN (
SELECT
[TLI_Location_ID]
FROM [TaLocationInformation]
)

INSERT INTO [TaLocationPersonalInformation]
(
[TLPI_Location_ID]
,[Competition]
,[Email_Address]
,[Exchange_Rate]
,[Existing_Sales_Rep]
,[Express_Location]
,[Financing_Type]
,[Lack_of_marketing]
,[Landlord_Issues]
,[Legal_Entity]
,[Market_Type]
,[MultiPurpose_Room]
,[No_Operating_Capital]
,[No_Sales_Revenue]
,[Online_Signup]
,[Open_Status]
,[Open_Temporary_Pending_Relo]
,[Other]
,[Other_Equipment]
,[Other_Operating_System]
,[Owner]
,[Partnership_Dispute]
,[Personal_Issues]
,[Personal_Training]
,[Primary_Contact]
,[Principal_Operator]
,[Principal_Owner]
,[Satellite_Club]
,[Site]
,[Stage]
,[Team_Workouts]
,[Veteran]
,[Virtual_Coaching]
,[Waxing_Account]
,[Website]
,[Active_CMS]
,[AFLP_Auto_Checklist]
,[AFLP_Inclub_Training_Lead]
,[AFLP_last_PostLaunch_Drip_email_sent]
,[AFLP_Marketing]
,[AFLP_Notes]
,[Billing_Account_Number]
,[Brand]
,[Club_OS]
,[Club_Ready]
,[Company]
,[Currency]
,[Main_Phone]
,[Renewal_Status]
,[Status]
,[Status_Reason]
,[Website_URL]
,[AFLP_Agreement]
,[Current_C2I]
)
SELECT 
[Location_ID]
,[Competition]
,[Email_Address]
,[Exchange_Rate]
,[Existing_Sales_Rep]
,[Express_Location]
,[Financing_Type]
,[Lack_of_marketing]
,[Landlord_Issues]
,[Legal_Entity]
,[Market_Type]
,[MultiPurpose_Room]
,[No_Operating_Capital]
,[No_Sales_Revenue]
,[Online_Signup]
,[Open_Status]
,[Open_Temporary_Pending_Relo]
,[Other]
,[Other_Equipment]
,[Other_Operating_System]
,[Owner]
,[Partnership_Dispute]
,[Personal_Issues]
,[Personal_Training]
,[Primary_Contact]
,[Principal_Operator]
,[Principal_Owner]
,[Satellite_Club]
,[Site]
,[Stage]
,[Team_Workouts]
,[Veteran]
,[Virtual_Coaching]
,[Waxing_Account]
,[Website]
,[Active_CMS]
,[AFLP_Auto_Checklist]
,[AFLP_Inclub_Training_Lead]
,[AFLP_last_PostLaunch_Drip_email_sent]
,[AFLP_Marketing]
,[AFLP_Notes]
,[Billing_Account_Number]
,[Brand]
,[Club_OS]
,[Club_Ready]
,[Company]
,[Currency]
,[Main_Phone]
,[Renewal_Status]
,[Status]
,[Status_Reason]
,[Website_URL]
,[AFLP_Agreement]
,[Current_C2I]
FROM [dbo].[TaLocationRaw]
WHERE [Location_ID] NOT IN (
SELECT
[TLPI_Location_ID]
FROM [TaLocationPersonalInformation]
)
INSERT INTO [TaLocation]
(
[Location_ID]
,[TLD_Location_ID]
,[TLI_Location_ID]
,[TLPI_Location_ID]
,[mile_pop_1]
,[mile_pop_3]
,[mile_pop_5]
,[AverageTerm]
,[Avg_monthly_gross_personal_training_revenue]
,[Gross_Rent]
,[Hours_of_Operation]
,[Median_income_50000]
,[Members_Dues_and_PIF]
,[Monthly_Fee_Amt]
,[MultiPurpose_Sq_Ft]
,[Number_of_Rooms]
,[Payroll]
,[Percent_Owner_1]
,[Percent_Owner_2]
,[Percent_Owner_3]
,[Percent_Owner_4]
,[Percent_Owner_5]
,[Percent_Owner_6]
,[Person_Training_Revenue]
,[Personal_Training_Revenue]
,[Problem_]
,[Profit_Loss]
,[Remit_Amount_Last_Quarter]
,[Remit_Amount_Quarter_Change]
,[Total_Contracts]
,[Transfer_Fee]
,[Utilities]
,[Average_Contract_Value]
,[Average_Member_Value]
,[BOE]
,[Draft_]
,[Dues]
,[Exited_Agreements]
,[Monthly_Attrition]
,[NEW_Agreements]
,[PIF_]
,[Remit_Amount]
,[Renewal_Fee]
,[Rolling_12_Month_Attrition]
,[Sq_Ft]
,[Total_Rent]
)
SELECT 
[Location_ID]
,[Location_ID]
,[Location_ID]
,[Location_ID]
,REPLACE([1_mile_pop],',','') AS [1_mile_pop]
,REPLACE([3_mile_pop],',','') AS [3_mile_pop]
,REPLACE([5_mile_pop],',','') AS [5_mile_pop]
,[AverageTerm]
,[Avg_monthly_gross_personal_training_revenue]
,[Gross_Rent]
,[Hours_of_Operation]
,[Median_income_50000]
,[Members_Dues_and_PIF]
,[Monthly_Fee_Amt]
,[MultiPurpose_Sq_Ft]
,[Number_of_Rooms]
,[Payroll]
,[Percent_Owner_1]
,[Percent_Owner_2]
,[Percent_Owner_3]
,[Percent_Owner_4]
,[Percent_Owner_5]
,[Percent_Owner_6]
,[Person_Training_Revenue]
,[Personal_Training_Revenue]
,[Problem_]
,[Profit_Loss]
,[Remit_Amount_Last_Quarter]
,[Remit_Amount_Quarter_Change]
,[Total_Contracts]
,[Transfer_Fee]
,[Utilities]
,[Average_Contract_Value]
,[Average_Member_Value]
,[BOE]
,[Draft_]
,[Dues]
,[Exited_Agreements]
,REPLACE([Monthly_Attrition],',','') AS [Monthly_Attrition]
,REPLACE([NEW_Agreements],',','') AS [NEW_Agreements]
,[PIF_]
,[Remit_Amount]
,[Renewal_Fee]
,[Rolling_12_Month_Attrition]
,[Sq_Ft]
,[Total_Rent]
FROM [dbo].[TaLocationRaw]
WHERE [Location_ID] NOT IN (
SELECT
[Location_ID]
FROM [TaLocation]
)
COMMIT TRANSACTION
END TRY
BEGIN CATCH
ROLLBACK TRANSACTION
SELECT ERROR_MESSAGE() AS Error_Msg
END CATCH
END   